name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore YOUR_SOLUTION_NAME.sln    # ← Replace with actual .sln file

    - name: Build
      run: dotnet build YOUR_SOLUTION_NAME.sln --no-restore --configuration Release    # ← Replace with actual .sln file

    - name: Test
      run: dotnet test YOUR_SOLUTION_NAME.sln --no-build --configuration Release --verbosity normal    # ← Replace with actual .sln file
